apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: hello-world-model
spec:
  protocol: v2
  predictors:
    - name: default
      graph:
        name: my-hello-world
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: my-hello-world
                image: my-hello-world:0.1